spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: pass@word1 # Change as per your setup
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

server:
  port: 8089 # Change port accordingly for each service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/ # Adjust based on your Eureka server URL
